fixtures:
  forge_modules:
    apt:
      repo: 'puppetlabs/apt'
      ref: '2.2.1'
    nodejs:
      repo: 'puppet/nodejs'
      ref: '1.3.0'
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.10.0'
  symlinks:
    npmo: "#{source_dir}"
