---
sudo: false
rvm:
  - 1.9.3
  - 2.1.7
language: ruby
bundler_args: --without development --clean
script: bundle exec rake spec
env:
  - PUPPET_GEM_VERSION="~> 3.7.0" FUTURE_PARSER="yes" STRICT_VARIABLES="yes"
  - PUPPET_GEM_VERSION="~> 3.8.0" FUTURE_PARSER="yes" STRICT_VARIABLES="yes"
  - PUPPET_GEM_VERSION="~> 3.8.1" FUTURE_PARSER="yes" STRICT_VARIABLES="yes"
  - PUPPET_GEM_VERSION="~> 3.8.2" FUTURE_PARSER="yes" STRICT_VARIABLES="yes"
  - PUPPET_GEM_VERSION="~> 3.8.3" FUTURE_PARSER="yes" STRICT_VARIABLES="yes"
  - PUPPET_GEM_VERSION="~> 3.8.4" FUTURE_PARSER="yes" STRICT_VARIABLES="yes"
  - PUPPET_GEM_VERSION="~> 4.0.0" STRICT_VARIABLES="yes"
  - PUPPET_GEM_VERSION="~> 4.1.0" STRICT_VARIABLES="yes"
  - PUPPET_GEM_VERSION="~> 4.2.0" STRICT_VARIABLES="yes"
  - PUPPET_GEM_VERSION="~> 4.2.1" STRICT_VARIABLES="yes"
  - PUPPET_GEM_VERSION="~> 4.2.2" STRICT_VARIABLES="yes"
  - PUPPET_GEM_VERSION="~> 4.2.3" STRICT_VARIABLES="yes"
  - PUPPET_GEM_VERSION="~> 4.3.0" STRICT_VARIABLES="yes"
  - PUPPET_GEM_VERSION="~> 4.3.1" STRICT_VARIABLES="yes"
matrix:
  # fast_finish: true
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 4.0.0" STRICT_VARIABLES="yes"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 4.1.0" STRICT_VARIABLES="yes"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 4.2.0" STRICT_VARIABLES="yes"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 4.2.1" STRICT_VARIABLES="yes"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 4.2.2" STRICT_VARIABLES="yes"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 4.2.3" STRICT_VARIABLES="yes"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 4.3.0" STRICT_VARIABLES="yes"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 4.3.1" STRICT_VARIABLES="yes"
notifications:
  email:
    - x3dfxjunkie@gmail.com
